#lang racket

 (require graphics/turtles)
 (require graphics/turtle-examples)
 
(turtles #t)
(define (draw_square_in_window)
  (split (turn/radians (/ pi 2)))
  (draw 50)
  (home)
  (turn/radians (/ pi 2))
  (move 50)
  (turn/radians (/ pi 2))
  (turn/radians (/ pi 2))
  (turn/radians (/ pi 2))
  (move 50)
  (turn/radians (/ pi 2))
  (turn/radians (/ pi 2))
  (split (turn/radians (/ pi 2)))
  (draw 50)
  (home)
)

(define (draw_olympics_symbol)
  (move -150)
  (regular-poly 100 50)
  (move 150)
  (regular-poly 100 50)
  (move 150)
  (regular-poly 100 50)
  (home)
  (move -150)
  (turn/radians (- 0 (/ pi 2)))
  (move 50)
  (turn/radians (/ pi 2))
  (move 75)
  (regular-poly 100 50)
  (move 150)
  (regular-poly 100 50)
  )