;Sokthai Tang 3/12/2017
#lang web-server/insta
(require web-server/servlet)
(define (start request)
  (response/xexpr
   '(html (head (title "Web Page")
                (link ((rel "stylesheet")
                       (href "/style.css")
                       (type "text/css"))))

          (body 
                (h1 "Registration Form")              
                (label "Username : ")
                (input ((name "username")))
                (br)(br)
                (label "Password : ")
                (input ((name "password")))
                (br)(br)
                (label "Name : ")
                (input ((name "name")))
                (br)(br)
                (label "Address : ")
                (input ((name "address")))
                (br)(br)
                (label "Country : ")
                (select (option "Select a country")
                        (option "United States")
                        (option "United Kingdom")
                        (option "Canada")
                ) 
                (br)(br)
                (label "Zipcode : ")
                (input ((name "zipcode")))
                (br)(br)
                (label "Email : ")
                (input ((type "email" name "email")))
                (br)(br)
                (input ((type "submit")))
          )
     )

   ))
 
(static-files-path "htdocs")